[package]
name = "raft-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project-lite = "0.2.14"
rand = "0.8"
rand_pcg = "0.3"
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
futures-test = "0.3"

