[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[dependencies]
raft-rs = { path = "..", features = ["testing"] }
rand = "0.8"
rand_pcg = "0.3"
s2n-codec = "0.51"
tokio = { version = "1", features = ["time", "test-util", "macros", "rt"] }
futures-test = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
futures-test = "0.3"
